on:
  push:
    branches:
      - "release/production"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}  # The repository to scan. owner/repo
        id: previoustag  # The step ID to refer to later.

      - run: echo "previoustag is ${{ steps.previoustag.outputs.tag }}"
      - run: echo "repository is ${{ github.repository }}"

      - name: Checkout code
        uses: actions/checkout@v2.2.0
      
      - run: | 
          git fetch --prune --unshallow --tags

      - name: Create changelogs
        id: changelogs
        uses: heineiuo/create-changelogs@master

      - run: echo "changelog is ${{ steps.changelogs.outputs.changelogs }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.previoustag.outputs.tag }}
          release_name: Release ${{ steps.previoustag.outputs.tag }}
          body: |
            ${{ steps.changelogs.outputs.changelogs }}
